### ISSUE TITLE
Simultaneous Multi Threading(SMT)

### ISSUE THREAD

**Issue by Cho-SangHyun** [tmdgusya/woowa-os-study#17]
책 237p에 나오는 기술로, 이해가 잘 되지 않아 따로 알아본 내용 정리해 공유합니다. 찾아보니 SMT기술의 대표적인 예로 인텔의 하이퍼스레딩이 있어서, 하이퍼스레딩에 대한 글들을 토대로 정리해봤습니다.

### 참조한 링크
https://www.intel.co.kr/content/www/kr/ko/gaming/resources/hyper-threading.html
https://donghoson.tistory.com/entry/%ED%95%98%EC%9D%B4%ED%8D%BC-%EC%8A%A4%EB%A0%88%EB%94%A9%EC%9D%B4%EB%9E%80-1

### 정리
- 원래는 특정 시점에서는 하나의 물리적인 CPU 코어에는 하나의 스레드(프로세스 스레드 할 때 그 스레드)만 돌아감. CPU 코어 하나에 하나의 실행 컨텍스트가 노출되기 때문
- 하이퍼스레딩이란, CPU 코어 하나가 "두 개의 실행 컨텍스트를 노출"시킴으로써 각 스레드들(프로세스 스레드 할 때 그 스레드)에게 해당 CPU 코어가 마치 서로 다른 CPU 코어인 것처럼 느껴지게 하는 것. 실제로는 하나의 물리적인 CPU 코어이나, 논리적으로는 2개의 CPU 코어가 있는 것처럼 보이게 한다고 표현
- 두 개의 실행 컨텍스트를 노출시켰다는 것은, 하나의 물리적인 CPU 코어에서 실제로 "동시"에 두 개의 작업이 돌아갈 수 있게 함을 의미. CPU 코어의 A라는 리소스와 B라는 리소스가 "동시"에 다른 작업을 할 수 있다.
- 하이퍼 스레딩이 없는 경우, 두 개의 스레드를 수행하는 데 걸리는 시간은 결국 각 스레드의 실행에 걸리는 시간의 합과 같음(사람에게는 동시에 수행되는 것처럼 보이나 특정 시간대에는 결국 하나의 작업만 돌아가고 있기 때문)
- 그러나 하이퍼 스레딩이 있다면 두 개의 스레드를 수행하는 데 걸리는 시간이 각 스레드의 실행에 걸리는 시간의 합보다 작을 수 있음(특정 시간대에 두 개의 작업이 "동시"에 돌아갈 수 있어서)
- 하나의 CPU 코어에서 여러 스레드를 병렬로 처리하며 CPU 점유율을 극한으로 쥐어짜는(?) 기술

### 궁금증
- 이론상(?) 하이퍼스레딩이 있다면, 두 스레드가 사용하는 자원이 겹치지 않는다면 효율이 매우 좋아집니다
- 두 스레드가 사용하는 자원이 겹쳐도, 결국 두 개의 스레드를 수행하는 데 걸리는 시간은 각 스레드의 실행에 걸리는 시간의 합과 같다고 예상됩니다(즉 하이퍼스레딩이 없는 경우 걸리는 시간)
- 그러나 두 개의 스레드가 사용하는 자원이 빈번히 겹치면 하이퍼스레딩은 오히려 하이퍼스레딩이 없을 때보다 성능이 더 나빠질 수 있다고 하는데, 이유가 뭔지는 알아볼 필요가 있을 것 같습니다.

**Comment by SINHOLEE** [comment]
오 덕분에 좋은 개념 익혀가요

https://donghoson.tistory.com/20

두번째 참조 링크의 2편 문서인데 이거가 찐으로 설명 잘해주네요

**Comment by SINHOLEE** [comment]
궁금증3 에서 하이퍼 스레딩의 경우 성능이 나빠질수 있다는 문구는 어디에 있을까요? 하이퍼스레딩은 1코어 1스레드에 비해 최소 보합 최대 2배효율이 맞는것같아요.

만약 책 248p에서 
> 오히려 SMT를 사용하지 않을때보다 성능이 나빠질 가능성도 있습니다.

이라면, 저는 이렇게 해석할거같아요

성능에는 두가지 방점이 있다.
1. 동일한 작업을 얼마나 빨리 끝내는가 <- 우리가 생각하는 성능의 개념
2. 가용률(단위처리마다 가지고 있는 cpu 자원을 최대한 많이 사용할수록 가용률이 높다.)

책에서 언급하는 성능 중, SMT 기법중 하나인 2코어2스레드 (윗 댓글의 링크에서 잘 설명해주네요)일때 가용률이 오히려 1코어 1스레드일때보다 낮아질 경우가 있네요.

**Comment by Cho-SangHyun** [comment]
@SINHOLEE 
무의식적으로 성능 = 소요시간으로 생각했었는데, 적어주신 걸 보고 나니 가용률 관점에서 성능을 바라볼 수도 있겠다는 생각이 드네요..
찾아보니 또다른 관점으로 전력소모(?)가 있던데.. 하이퍼쓰레딩을 켜면 전력소모가 늘기 때문에, 물리 코어 여유가 있다면 하이퍼쓰레딩을 끄는게 더 낫다고 합니다.
또 찾아보니 하이퍼스레딩이 켜진 상태에서 두 개(혹은 그 이상)의 스레드가 사용하는 자원이 빈번히 겹치면, 한 스레드만 코어 위에서 돌아갈 때와는 달리 자원에 대한 경합 상태가 발생하고 그로 인한 오버헤드가 조금씩 있기 때문에, 소요 시간 자체도 조금씩 늘어나는 경우가 있다고 합니다.

하나의 관점에서만 성능을 바라보면 안되고, 여러 관점에서 볼 수 있어야겠다는 생각이 듭니다! 덕분에 감사합니다 :)
