### ISSUE TITLE
man page

### ISSUE THREAD

**Issue by nainu** [tmdgusya/woowa-os-study#4]
터미널에서 `man cc` 요렇게 해도 man7 과 동일한 페이지를 볼 수 있네요. 

https://ko.wikipedia.org/wiki/Man_page

자세한 (모든) 설명은 위 페이지에...

**Comment by tmdgusya** [comment]
@nainu 오 ㅋㅋ 좋네요 grep 이랑 연계도되서 보기 편하군요
