### ISSUE TITLE
정적 링크 vs 동적 링크

### ISSUE THREAD

**Issue by koyrkr** [tmdgusya/woowa-os-study#5]
p.44에서 다음과 같은 이유로 정적 링크를 사용한다고 했는데요,

> - 실행 파일 하나로 프로그램이 동작한다면 해당 파일만 복사하면 다른 환경에서도 동작하므로 사용이 편리합니다.

이 말은, 동적 링크의 경우는 실행 파일 뿐만 아니라 관련된 라이브러리 정보(및 파일)도 함께 복사되어야 하는 반면에, 정적 링크의 경우는 단순히 그 파일만 복사해도 문제없이 동작할 수 있다는 의미가 맞나요? 

제대로 이해한건지 확인차 남겨봅니다! 다른 첨언들도 환영입니다.

**Comment by tmdgusya** [comment]
네, Go 같은 경우 컴파일 되어서 실행 가능한 파일(Executable file) 로 됬을때 별도로 의존성들을 요구하지 않아요. Js 의 경우 실행 환경에 lib 들을 설치하지 않으면 (npm install 등등의 command 를 통해) 실행되지 않던걸로 기억해요.

**Comment by tmdgusya** [comment]
그래서 Go build 같은 경우에는 원하는 실행환경(linux, maxOs, WindowOs, etc) 에 따라 빌드가 가능해요.
